name: Publish .mcaddon

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create .mcaddon
      run: |
        cd BP
        zip -r BP.zip *
        mv BP.zip ../BP.mcaddon
        cd ../RP
        zip -r RP.zip *
        mv RP.zip ../RP.mcaddon
        cd ..
        zip -r myaddon.zip BP.mcaddon RP.mcaddon
        mv myaddon.zip myaddon.mcaddon

    - name: Upload .mcaddon
      uses: actions/upload-artifact@v2
      with:
        name: capybaras-mod-${{ env.GITHUB_REF }}.mcaddon
        path: myaddon.mcaddon
